# logger_name
# logger_level
# logger_file
logger:
  name: python25
  level: WARNING
  file: '/log.txt'

database:
  host: '120.78.128.25'
  port: 3306
  user: 'future'
  password: '123456'
  charset: 'utf8'
  database: 'futureloan'

user:
  mobile_phone: '18298000000'
  pwd: '12345678'
